spring:
  application:
    name: TestApplication

server:
  port: 8086

management:
  endpoints:
    web:
      exposure:
        include: '*'
env: dev  

owner:
  name: killer
hello:
  rel: dev dj
  
