server:
  port: 8082
spring:
  application:
    # name: application-dev if the value of the spring.application.name such as ""application-dev"" this can be used to retrieve application-dev.yml from git. worked on 02/13/2021.
    # name: config-client  if the value of the spring.application.name such as "config-client" doesn't match with any property files from git, it will pick the application.yml
    name:  clinic-management-service

## Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
spring.datasource.url: "jdbc:mysql://localhost:3306/world?useSSL=false"
spring.datasource.username: "root"
spring.datasource.password : "admin"
spring.jpa.properties.hibernate.dialect: "org.hibernate.dialect.MySQL5Dialect"
spring.jpa.database-platform: "org.hibernate.dialect.MySQL5Dialect"
spring.datasource.driver-class-name: "com.mysql.cj.jdbc.Driver"

# spring.jpa.generate-ddl=true  will generate tables for us
spring.jpa.generate-ddl: "true" 
spring.jpa.hibernate.ddl-auto: "update"
spring.jpa.show-sql: "true"

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
